export interface Product {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  description: string;
  specs: string[];
  features: string[];
  icon: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  productCount: number;
}

export interface Service {
  id: string;
  name: string;
  icon: string;
  description: string;
  details: string[];
}

export const categories: Category[] = [
  {
    id: 'ganaderas',
    name: 'Basculas Ganaderas',
    icon: 'leaf-outline',
    description: 'Barras portatiles, plataformas y kits ganaderos completos',
    productCount: 10,
  },
  {
    id: 'camioneras',
    name: 'Basculas Camioneras',
    icon: 'car-outline',
    description: 'Tipo puente, modulares, pesaje por ejes y obra civil',
    productCount: 4,
  },
  {
    id: 'bretes',
    name: 'Bretes y Jaulas',
    icon: 'grid-outline',
    description: 'Bretes ganaderos, jaulas porcinas y mecanicas',
    productCount: 4,
  },
  {
    id: 'avicola',
    name: 'Clasificadora de Huevos',
    icon: 'ellipse-outline',
    description: 'Maquinas clasificadoras para la industria avicola',
    productCount: 2,
  },
  {
    id: 'cirugia',
    name: 'Mesa de Cirugia Bovina',
    icon: 'medkit-outline',
    description: 'Mesas especializadas para procedimientos veterinarios',
    productCount: 2,
  },
  {
    id: 'ordenos',
    name: 'Equipos de Ordeño',
    icon: 'water-outline',
    description: 'Sistemas de ordeño mecanico y automatizado',
    productCount: 3,
  },
  {
    id: 'esterilizador',
    name: 'Equipo Esterilizador',
    icon: 'flame-outline',
    description: 'Equipos de esterilizacion para la industria lactea',
    productCount: 2,
  },
  {
    id: 'descremador',
    name: 'Descremadores',
    icon: 'sync-outline',
    description: 'Descremadoras de leche para produccion artesanal e industrial',
    productCount: 2,
  },
  {
    id: 'alimento',
    name: 'Maquinaria para Alimento',
    icon: 'nutrition-outline',
    description: 'Picadoras, mezcladoras y molinos para alimento animal',
    productCount: 3,
  },
  {
    id: 'frios',
    name: 'Cuartos Frios',
    icon: 'snow-outline',
    description: 'Cuartos frios y plantas industriales de procesamiento',
    productCount: 2,
  },
];

export const products: Product[] = [
  {
    id: 'barras-hw1500',
    name: 'Barras HW1500',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Barras de pesaje portatiles con capacidad de 1500 kg. Sistema practico y facil de transportar para uso en campo.',
    specs: ['Capacidad: 1,500 Kg', 'Tipo: Portatil', 'Display: LED', 'Bateria: Recargable'],
    features: ['Portatil y liviana', 'Display LED de alta visibilidad', 'Bateria de larga duracion', 'Facil transporte'],
    icon: 'barbell-outline',
  },
  {
    id: 'barras-hw2000',
    name: 'Barras HW2000',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Barras de pesaje portatiles con capacidad de 2000 kg. Alta precision para pesaje de ganado en campo.',
    specs: ['Capacidad: 2,000 Kg', 'Tipo: Portatil', 'Display: LED', 'Conexion: RS232'],
    features: ['Capacidad 2 toneladas', 'Conexion a PC', 'Precision certificada', 'Facil instalacion'],
    icon: 'barbell-outline',
  },
  {
    id: 'barras-hw2000-fa',
    name: 'Barras HW2000-FA',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Version mejorada con funciones avanzadas de pesaje. Incluye funcion de estabilizacion y acumulador.',
    specs: ['Capacidad: 2,000 Kg', 'Funciones: Avanzadas', 'Estabilizador: Si', 'Acumulador: Si'],
    features: ['Funcion estabilizadora', 'Acumulador de pesajes', 'Promediado automatico', 'Uso intensivo'],
    icon: 'barbell-outline',
  },
  {
    id: 'barras-hw2000-ss',
    name: 'Barras HW2000-SS',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Barras de pesaje en acero inoxidable. Maxima durabilidad y resistencia a la corrosion para ambientes exigentes.',
    specs: ['Capacidad: 2,000 Kg', 'Material: Acero inoxidable', 'Resistencia: Anti-corrosion', 'Uso: Intensivo'],
    features: ['Acero inoxidable', 'Anti-corrosion', 'Maxima durabilidad', 'Ambientes exigentes'],
    icon: 'barbell-outline',
  },
  {
    id: 'barras-hw3000',
    name: 'Barras HW3000',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Barras de pesaje de alta capacidad en acero inoxidable. Ideal para ganado mayor y pesaje de grandes volumenes.',
    specs: ['Capacidad: 3,000 Kg', 'Material: Acero inoxidable', 'Display: LED', 'Proteccion: IP65'],
    features: ['Alta capacidad', 'Acero inoxidable', 'Proteccion IP65', 'Gran volumen'],
    icon: 'barbell-outline',
  },
  {
    id: 'barras-hw3500',
    name: 'Barras HW3500',
    category: 'Bascula Ganadera Portatil',
    categoryId: 'ganaderas',
    description: 'Barras de pesaje maxima capacidad 3500 kg. La solucion mas robusta para pesaje de ganado bovino de gran tamaño.',
    specs: ['Capacidad: 3,500 Kg', 'Tipo: Portatil HD', 'Resistencia: Maxima', 'Garantia: 36 meses'],
    features: ['Maxima capacidad', 'Uso pesado', 'Resistencia extrema', 'Garantia extendida'],
    icon: 'barbell-outline',
  },
  {
    id: 'kit-ganadero',
    name: 'Kit Ganadero Plataforma + Bascula',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Kit completo con plataforma en aluminio y bascula electronica. Indicador ABS con display LED, bateria recargable de 42 horas. Capacidad 2000-3000 Kg.',
    specs: ['Capacidad: 2,000-3,000 Kg', 'Bateria: 42 horas', 'Plataforma: Aluminio 2.20x60cm', 'Puerto: RS232'],
    features: ['Indicador ABS', 'Estabilizar peso en movimiento', 'Conexion PC / impresion tiquetes', 'Proteccion IP65'],
    icon: 'layers-outline',
  },
  {
    id: 'bascula-plataforma-acero',
    name: 'Bascula Plataforma en Acero',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Bascula de plataforma fabricada en acero de alta resistencia. Diseño robusto para uso continuo en fincas ganaderas.',
    specs: ['Material: Acero reforzado', 'Capacidad: Variable', 'Uso: Continuo', 'Diseño: Robusto'],
    features: ['Acero de alta resistencia', 'Uso continuo', 'Diseño robusto', 'Facil limpieza'],
    icon: 'layers-outline',
  },
  {
    id: 'pesas-patron',
    name: 'Pesas Patron E2, F1 y F2',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Estuche de pesas patron E2, F1 y F2 en acero inoxidable o acero cromado. Para calibracion y verificacion.',
    specs: ['Clases: E2, F1, F2', 'Material: Acero inoxidable/cromado', 'Rango: 1g a 5Kg', 'Certificacion: SI'],
    features: ['Precision certificada', 'Acero inoxidable', 'Estuche incluido', 'Multiples clases'],
    icon: 'diamond-outline',
  },
  {
    id: 'masas-patron',
    name: 'Masas Patron Cilindricas',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Masas patron cilindricas desde 1g hasta 5 Kg. Pesas M1 o M2 en hierro gris fundido con tapon de bronce.',
    specs: ['Rango: 1g a 50Kg', 'Clases: M1, M2', 'Material: Hierro fundido', 'Tapon: Bronce'],
    features: ['Amplio rango', 'Hierro fundido', 'Tapon de bronce', 'Calibracion precisa'],
    icon: 'diamond-outline',
  },
  {
    id: 'camionera-puente',
    name: 'Bascula Camionera Tipo Puente',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Bascula camionera tipo puente con barandas y plataforma en concreto BAC-18360T. Diseño robusto para pesaje de vehiculos pesados.',
    specs: ['Modelo: BAC-18360T', 'Plataforma: Concreto', 'Tipo: Puente con barandas', 'Capacidad: Alta'],
    features: ['Plataforma en concreto', 'Barandas de seguridad', 'Uso pesado', 'Alta durabilidad'],
    icon: 'car-outline',
  },
  {
    id: 'camionera-modular',
    name: 'Bascula Camionera Modular 21m',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Bascula camionera electronica con plataforma de rodamiento en concreto modular de 21 metros. Para operaciones de gran escala.',
    specs: ['Longitud: 21 metros', 'Plataforma: Concreto modular', 'Tipo: Electronica', 'Rodamiento: Concreto'],
    features: ['21 metros de longitud', 'Modular', 'Electronica digital', 'Gran escala'],
    icon: 'car-outline',
  },
  {
    id: 'camionera-ejes',
    name: 'Bascula Camionera Pesaje por Ejes',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Sistema de pesaje por ejes para vehiculos en movimiento. Solucion eficiente para control de carga en carreteras.',
    specs: ['Tipo: Pesaje por ejes', 'Uso: Vehiculos en movimiento', 'Control: Carga', 'Instalacion: Carreteras'],
    features: ['Pesaje en movimiento', 'Control de carga', 'Eficiencia operativa', 'Facil instalacion'],
    icon: 'car-outline',
  },
  {
    id: 'camionera-bac21',
    name: 'Bascula Camionera BAC21-100T',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Bascula camionera con aprobacion de modelo BAC21-100T. Capacidad de 100 toneladas con certificacion oficial.',
    specs: ['Modelo: BAC21-100T', 'Capacidad: 100 Toneladas', 'Certificacion: Aprobacion de modelo', 'Tipo: Certificada'],
    features: ['100 toneladas', 'Aprobacion de modelo', 'Certificacion oficial', 'Maxima precision'],
    icon: 'car-outline',
  },
  {
    id: 'brete-inoxidable',
    name: 'Brete Ganadero Acero Inoxidable',
    category: 'Bretes y Jaulas',
    categoryId: 'bretes',
    description: 'Brete ganadero fabricado en acero inoxidable de alta resistencia. Diseño ergonomico para manejo seguro del ganado.',
    specs: ['Material: Acero inoxidable', 'Diseño: Ergonomico', 'Uso: Ganado bovino', 'Resistencia: Alta'],
    features: ['Acero inoxidable', 'Manejo seguro', 'Diseño ergonomico', 'Alta resistencia'],
    icon: 'grid-outline',
  },
  {
    id: 'jaula-porcina',
    name: 'Jaula Porcina',
    category: 'Bretes y Jaulas',
    categoryId: 'bretes',
    description: 'Jaula especializada para pesaje y manejo de porcinos. Estructura resistente con facil acceso y cierre seguro.',
    specs: ['Uso: Porcinos', 'Material: Acero', 'Acceso: Facil', 'Cierre: Seguro'],
    features: ['Especializada para porcinos', 'Acceso facil', 'Cierre seguro', 'Estructura resistente'],
    icon: 'grid-outline',
  },
  {
    id: 'jaula-mecanica',
    name: 'Jaula Mecanica',
    category: 'Bretes y Jaulas',
    categoryId: 'bretes',
    description: 'Jaula mecanica para manejo de ganado. Sistema mecanico confiable sin necesidad de energia electrica.',
    specs: ['Tipo: Mecanica', 'Electricidad: No requiere', 'Operacion: Manual', 'Durabilidad: Alta'],
    features: ['Sin electricidad', 'Operacion manual', 'Confiable', 'Baja mantencion'],
    icon: 'grid-outline',
  },
  {
    id: 'brete-estandar',
    name: 'Brete Ganadero Estandar',
    category: 'Bretes y Jaulas',
    categoryId: 'bretes',
    description: 'Brete ganadero estandar para manejo y pesaje de bovinos. Construccion solida con puertas de acceso frontal y lateral.',
    specs: ['Material: Acero galvanizado', 'Puertas: Frontal y lateral', 'Uso: Bovinos', 'Construccion: Solida'],
    features: ['Acero galvanizado', 'Doble puerta', 'Facil operacion', 'Construccion solida'],
    icon: 'grid-outline',
  },
  {
    id: 'clasificadora-huevos',
    name: 'Clasificadora de Huevos Automatica',
    category: 'Clasificadora de Huevos',
    categoryId: 'avicola',
    description: 'Maquina clasificadora de huevos automatica para la industria avicola. Seleccion por peso y tamaño con alta velocidad.',
    specs: ['Tipo: Automatica', 'Clasificacion: Por peso', 'Velocidad: Alta', 'Industria: Avicola'],
    features: ['Clasificacion automatica', 'Por peso y tamaño', 'Alta velocidad', 'Industria avicola'],
    icon: 'ellipse-outline',
  },
  {
    id: 'clasificadora-semi',
    name: 'Clasificadora de Huevos Semi-Automatica',
    category: 'Clasificadora de Huevos',
    categoryId: 'avicola',
    description: 'Clasificadora semi-automatica ideal para produccion mediana. Facil operacion con clasificacion precisa por peso.',
    specs: ['Tipo: Semi-automatica', 'Produccion: Mediana', 'Operacion: Facil', 'Clasificacion: Por peso'],
    features: ['Semi-automatica', 'Produccion mediana', 'Facil operacion', 'Precio accesible'],
    icon: 'ellipse-outline',
  },
  {
    id: 'mesa-cirugia',
    name: 'Mesa de Cirugia Bovina',
    category: 'Mesa de Cirugia',
    categoryId: 'cirugia',
    description: 'Mesa de cirugia bovina hidraulica para procedimientos veterinarios. Permite inmovilizar al animal de forma segura.',
    specs: ['Tipo: Hidraulica', 'Uso: Cirugia bovina', 'Seguridad: Alta', 'Material: Acero'],
    features: ['Sistema hidraulico', 'Inmovilizacion segura', 'Procedimientos veterinarios', 'Acero resistente'],
    icon: 'medkit-outline',
  },
  {
    id: 'mesa-cirugia-manual',
    name: 'Mesa de Cirugia Manual',
    category: 'Mesa de Cirugia',
    categoryId: 'cirugia',
    description: 'Mesa de cirugia bovina con sistema manual. Solucion practica y economica para procedimientos veterinarios en campo.',
    specs: ['Tipo: Manual', 'Uso: Campo', 'Economia: Alta', 'Portabilidad: Si'],
    features: ['Sistema manual', 'Economica', 'Uso en campo', 'Facil transporte'],
    icon: 'medkit-outline',
  },
  {
    id: 'ordeno-mecanico',
    name: 'Ordeño Mecanico Portatil',
    category: 'Equipos de Ordeño',
    categoryId: 'ordenos',
    description: 'Sistema de ordeño mecanico portatil para fincas ganaderas. Facil de transportar e instalar, ideal para pequeñas y medianas producciones.',
    specs: ['Tipo: Portatil', 'Puntos: 1-2', 'Motor: Electrico', 'Transporte: Facil'],
    features: ['Portatil', 'Facil instalacion', 'Motor electrico', 'Higienico'],
    icon: 'water-outline',
  },
  {
    id: 'ordeno-fijo',
    name: 'Ordeño Fijo en Sala',
    category: 'Equipos de Ordeño',
    categoryId: 'ordenos',
    description: 'Sistema de ordeño fijo para salas de ordeño. Alta capacidad de procesamiento para ganaderias grandes.',
    specs: ['Tipo: Fijo', 'Capacidad: Alta', 'Instalacion: Sala', 'Puntos: Multiples'],
    features: ['Alta capacidad', 'Multiples puntos', 'Sala de ordeño', 'Automatizado'],
    icon: 'water-outline',
  },
  {
    id: 'ordeno-tubular',
    name: 'Ordeño Tubular',
    category: 'Equipos de Ordeño',
    categoryId: 'ordenos',
    description: 'Sistema de ordeño con linea tubular para conduccion de leche. Maxima higiene y eficiencia en la recoleccion.',
    specs: ['Tipo: Tubular', 'Conduccion: Linea cerrada', 'Higiene: Maxima', 'Eficiencia: Alta'],
    features: ['Linea tubular', 'Maxima higiene', 'Conduccion cerrada', 'Alta eficiencia'],
    icon: 'water-outline',
  },
  {
    id: 'esterilizador-leche',
    name: 'Esterilizador de Leche',
    category: 'Equipo Esterilizador',
    categoryId: 'esterilizador',
    description: 'Equipo esterilizador para procesamiento de leche. Garantiza la eliminacion de microorganismos y maxima calidad del producto.',
    specs: ['Proceso: Esterilizacion', 'Producto: Leche', 'Capacidad: Variable', 'Temperatura: Controlada'],
    features: ['Esterilizacion completa', 'Control de temperatura', 'Calidad garantizada', 'Uso industrial'],
    icon: 'flame-outline',
  },
  {
    id: 'pasteurizador',
    name: 'Pasteurizador Industrial',
    category: 'Equipo Esterilizador',
    categoryId: 'esterilizador',
    description: 'Pasteurizador para procesamiento de lacteos. Control preciso de temperatura para pasteurizacion lenta o rapida.',
    specs: ['Tipo: Pasteurizador', 'Control: Temperatura preciso', 'Modos: Lenta / Rapida', 'Uso: Lacteos'],
    features: ['Pasteurizacion precisa', 'Dos modos', 'Control digital', 'Lacteos'],
    icon: 'flame-outline',
  },
  {
    id: 'descremador-leche',
    name: 'Descremador de Leche',
    category: 'Descremadores',
    categoryId: 'descremador',
    description: 'Descremadora de leche para separacion de crema. Ideal para produccion artesanal e industrial de derivados lacteos.',
    specs: ['Tipo: Centrifugo', 'Producto: Leche', 'Produccion: Artesanal/Industrial', 'Motor: Electrico'],
    features: ['Separacion centrifuga', 'Artesanal e industrial', 'Motor electrico', 'Facil operacion'],
    icon: 'sync-outline',
  },
  {
    id: 'descremador-industrial',
    name: 'Descremador Industrial',
    category: 'Descremadores',
    categoryId: 'descremador',
    description: 'Descremadora de alta capacidad para plantas de procesamiento. Separacion eficiente de crema con alto rendimiento.',
    specs: ['Capacidad: Alta', 'Uso: Plantas', 'Rendimiento: Alto', 'Tipo: Industrial'],
    features: ['Alta capacidad', 'Uso en plantas', 'Alto rendimiento', 'Automatizado'],
    icon: 'sync-outline',
  },
  {
    id: 'picadora-pasto',
    name: 'Picadora de Pasto',
    category: 'Maquinaria para Alimento',
    categoryId: 'alimento',
    description: 'Picadora de pasto y forraje para preparacion de alimento animal. Alta velocidad de procesamiento con corte uniforme.',
    specs: ['Tipo: Picadora', 'Material: Pasto/Forraje', 'Corte: Uniforme', 'Motor: Electrico/Diesel'],
    features: ['Corte uniforme', 'Alta velocidad', 'Versatil', 'Motor potente'],
    icon: 'nutrition-outline',
  },
  {
    id: 'mezcladora-alimento',
    name: 'Mezcladora de Alimento',
    category: 'Maquinaria para Alimento',
    categoryId: 'alimento',
    description: 'Mezcladora para preparacion de raciones alimenticias. Mezcla homogenea de ingredientes para nutricion animal.',
    specs: ['Tipo: Mezcladora', 'Mezcla: Homogenea', 'Capacidad: Variable', 'Uso: Raciones'],
    features: ['Mezcla homogenea', 'Capacidad variable', 'Facil carga', 'Raciones balanceadas'],
    icon: 'nutrition-outline',
  },
  {
    id: 'molino-alimento',
    name: 'Molino para Alimento',
    category: 'Maquinaria para Alimento',
    categoryId: 'alimento',
    description: 'Molino para procesamiento de granos y alimento animal. Molienda fina y gruesa segun necesidad.',
    specs: ['Tipo: Molino', 'Producto: Granos', 'Molienda: Ajustable', 'Motor: Electrico'],
    features: ['Molienda ajustable', 'Granos y cereales', 'Motor electrico', 'Alta produccion'],
    icon: 'nutrition-outline',
  },
  {
    id: 'cuarto-frio',
    name: 'Cuarto Frio Industrial',
    category: 'Cuartos Frios',
    categoryId: 'frios',
    description: 'Cuartos frios para conservacion de productos carnicos y lacteos. Temperatura controlada con paneles aislantes de alta eficiencia.',
    specs: ['Tipo: Industrial', 'Temperatura: Controlada', 'Paneles: Aislantes', 'Uso: Carnicos/Lacteos'],
    features: ['Temperatura controlada', 'Paneles aislantes', 'Alta eficiencia', 'Uso carnicos'],
    icon: 'snow-outline',
  },
  {
    id: 'planta-procesamiento',
    name: 'Planta de Procesamiento Industrial',
    category: 'Cuartos Frios',
    categoryId: 'frios',
    description: 'Diseño e instalacion de plantas industriales de procesamiento carnico y lacteo. Solucion integral llave en mano.',
    specs: ['Tipo: Planta completa', 'Diseño: A medida', 'Instalacion: Incluida', 'Entrega: Llave en mano'],
    features: ['Solucion integral', 'Diseño a medida', 'Instalacion completa', 'Llave en mano'],
    icon: 'snow-outline',
  },
];

export const services: Service[] = [
  {
    id: 'venta',
    name: 'Venta de Equipos',
    icon: 'cart-outline',
    description: 'Venta directa de toda nuestra linea de productos para la industria carnica, lactea y ganadera con asesoria personalizada.',
    details: [
      'Catalogo completo de productos',
      'Asesoria personalizada',
      'Precios competitivos',
      'Despacho a todo Colombia',
      'Facturacion electronica',
      'Garantia de fabrica 36 meses',
    ],
  },
  {
    id: 'instalacion',
    name: 'Instalacion y Montaje',
    icon: 'construct-outline',
    description: 'Servicio profesional de instalacion y montaje de equipos. Nuestro equipo tecnico asegura la correcta puesta en marcha.',
    details: [
      'Instalacion profesional',
      'Montaje in situ',
      'Puesta en marcha',
      'Capacitacion de personal',
      'Pruebas de funcionamiento',
      'Entrega de manuales',
    ],
  },
  {
    id: 'mantenimiento',
    name: 'Mantenimiento y Soporte',
    icon: 'build-outline',
    description: 'Servicio de mantenimiento preventivo y correctivo para todos nuestros equipos. Cobertura nacional con repuestos originales.',
    details: [
      'Mantenimiento preventivo',
      'Mantenimiento correctivo',
      'Repuestos originales',
      'Cobertura nacional',
      'Diagnostico tecnico',
      'Atencion oportuna',
    ],
  },
  {
    id: 'calibracion',
    name: 'Calibracion de Basculas',
    icon: 'analytics-outline',
    description: 'Servicio de calibracion de basculas con pesas patron certificadas. Garantizamos la precision de sus equipos de pesaje.',
    details: [
      'Pesas patron certificadas',
      'Certificado de calibracion',
      'Ajuste de precision',
      'Verificacion periodica',
      'Personal calificado',
      'Normativa vigente',
    ],
  },
  {
    id: 'asesoria',
    name: 'Asesoria Tecnica',
    icon: 'school-outline',
    description: 'Asesoria tecnica especializada para seleccionar la solucion ideal segun su necesidad productiva y presupuesto.',
    details: [
      'Evaluacion de necesidades',
      'Recomendacion de equipos',
      'Diseño de soluciones',
      'Capacitacion tecnica',
      'Acompañamiento',
      'Soporte post-venta',
    ],
  },
  {
    id: 'obra-civil',
    name: 'Obra Civil',
    icon: 'business-outline',
    description: 'Diseño y construccion de obra civil para instalacion de basculas camioneras y plantas de procesamiento.',
    details: [
      'Diseño de cimentacion',
      'Construccion de rampas',
      'Obra civil para basculas',
      'Adecuaciones de planta',
      'Pisos industriales',
      'Permisos y licencias',
    ],
  },
];

export const companyInfo = {
  name: 'SOFTGAN',
  tagline: 'Soluciones para la Industria Carnica, Lactea y Ganadera',
  slogan: 'Tecnologia al servicio del campo',
  phone: '+57 301 105 7567',
  whatsapp: '+573163263971',
  email: 'comercial@softgan.com',
  website: 'www.softgan.com',
  facebook: 'basculassoftgan',
  instagram: 'softgantech',
  youtube: 'SOFTGAN',
  asesora: 'Carolina',
  sectors: [
    'Ganaderia bovina',
    'Ganaderia porcina',
    'Industria carnica',
    'Industria lactea',
    'Industria avicola',
    'Agroindustria',
    'Plantas de procesamiento',
    'Fincas ganaderas',
  ],
  advantages: [
    'Soluciones integrales para el campo',
    'Equipos de alta calidad y durabilidad',
    'Garantia de 36 meses por defectos de fabricacion',
    'Disponibilidad de repuestos (Life Warranty)',
    'Despacho a todo Colombia',
    'Asesoria tecnica personalizada',
    'Instalacion y montaje profesional',
    'Soporte post-venta continuo',
  ],
  stats: {
    clients: '500+',
    projects: '1,000+',
    maintenances: '2,500+',
    consultations: '3,000+',
  },
};
