export interface Product {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  description: string;
  specs: string[];
  features: string[];
  image: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  productCount: number;
}

export interface Service {
  id: string;
  name: string;
  icon: string;
  description: string;
  details: string[];
}

export const categories: Category[] = [
  {
    id: 'industriales',
    name: 'Basculas Industriales',
    icon: 'cube-outline',
    description: 'Plataforma, mesa, waterproof, washdown y especializadas',
    productCount: 8,
  },
  {
    id: 'ganaderas',
    name: 'Basculas Ganaderas',
    icon: 'leaf-outline',
    description: 'Electronicas y mecanicas para pesaje de ganado',
    productCount: 4,
  },
  {
    id: 'camioneras',
    name: 'Basculas Camioneras',
    icon: 'car-outline',
    description: 'Diseño y fabricacion a medida para vehiculos pesados',
    productCount: 3,
  },
  {
    id: 'dinamometros',
    name: 'Dinamometros',
    icon: 'fitness-outline',
    description: 'Capacidades hasta 10 toneladas con control remoto',
    productCount: 3,
  },
  {
    id: 'perifericos',
    name: 'Perifericos y Accesorios',
    icon: 'settings-outline',
    description: 'Indicadores, displays, celdas de carga, pesas patron',
    productCount: 6,
  },
  {
    id: 'software',
    name: 'Software',
    icon: 'desktop-outline',
    description: 'Software camionero, molinos, peajes y a la medida',
    productCount: 4,
  },
];

export const products: Product[] = [
  {
    id: 'bascula-plataforma-electronica',
    name: 'Bascula de Plataforma Electronica',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula electronica de plataforma con indicador digital, diseño modular para armado facil. Estructuras que facilitan limpieza, resistentes a condiciones exigentes.',
    specs: ['Capacidad: Variable segun modelo', 'Material: Acero galvanizado / inoxidable', 'Proteccion: IP54 a IP67', 'Dimensiones: Personalizables'],
    features: ['Diseño modular', '100% reparable', 'Compatible con indicadores digitales', 'Estructura de facil limpieza'],
    image: 'scale-platform',
  },
  {
    id: 'bascula-mesa-precision',
    name: 'Bascula de Mesa Alta Precision',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula de mesa con alta precision, Clase II y Clase III OIML. Display LED dual con funciones avanzadas de pesaje.',
    specs: ['Clase: II y III OIML', 'Display: LED dual', 'Proteccion: IP55', 'Alimentacion: Bateria recargable'],
    features: ['Funcion ZERO y TARA', 'Cuenta piezas', 'Acumulacion de pesajes', 'Bateria recargable'],
    image: 'scale-table',
  },
  {
    id: 'bascula-waterproof',
    name: 'Bascula Waterproof',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula hermeticamente sellada con estandar WATERPROOF. Ideal para ambientes humedos y lavado frecuente.',
    specs: ['Estandar: WATERPROOF', 'Sellado: Hermetico', 'Uso: Ambientes humedos', 'Sector: Alimentos'],
    features: ['Hermeticamente sellada', 'Resistente a lavado', 'Ideal para alimentos', 'Alta durabilidad'],
    image: 'scale-waterproof',
  },
  {
    id: 'bascula-washdown',
    name: 'Bascula Washdown',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula diseñada para lavado frecuente, especial para el sector de alimentos con maxima higiene.',
    specs: ['Diseño: Washdown', 'Sector: Alimentos', 'Limpieza: Lavado frecuente', 'Material: Acero inoxidable'],
    features: ['Diseñada para lavado', 'Sector alimentos', 'Maxima higiene', 'Acero inoxidable'],
    image: 'scale-washdown',
  },
  {
    id: 'bascula-agricola',
    name: 'Bascula Sector Agricola',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula robusta y facil de transportar, especialmente diseñada para el sector agricola y ambientes rurales.',
    specs: ['Uso: Sector agricola', 'Diseño: Robusto y portatil', 'Resistencia: Condiciones rurales', 'Transporte: Facil'],
    features: ['Robusta y portatil', 'Facil transporte', 'Resistente al campo', 'Alta durabilidad'],
    image: 'scale-agri',
  },
  {
    id: 'bascula-anticorrosiva',
    name: 'Bascula Ambientes Corrosivos',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula con alta resistencia a la corrosion, ideal para ambientes quimicos y condiciones extremas.',
    specs: ['Resistencia: Anti-corrosion', 'Uso: Ambientes quimicos', 'Material: Especial', 'Proteccion: Maxima'],
    features: ['Alta resistencia a corrosion', 'Ambientes quimicos', 'Materiales especiales', 'Larga vida util'],
    image: 'scale-corrosive',
  },
  {
    id: 'bascula-electromecanica',
    name: 'Bascula Electromecanica',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula electromecanica que combina la robustez mecanica con la precision electronica, ideal para uso industrial intensivo.',
    specs: ['Tipo: Electromecanica', 'Capacidad: Variable', 'Precision: Alta', 'Uso: Industrial intensivo'],
    features: ['Combina mecanica y electronica', 'Alta precision', 'Uso intensivo', 'Facil mantenimiento'],
    image: 'scale-electromech',
  },
  {
    id: 'bascula-analoga',
    name: 'Bascula Electronica Analoga',
    category: 'Basculas Industriales',
    categoryId: 'industriales',
    description: 'Bascula electronica con lectura analoga, practica y confiable para uso industrial diario.',
    specs: ['Tipo: Electronica analoga', 'Lectura: Analoga', 'Uso: Industrial diario', 'Confiabilidad: Alta'],
    features: ['Lectura analoga clara', 'Uso diario', 'Alta confiabilidad', 'Facil operacion'],
    image: 'scale-analog',
  },
  {
    id: 'bascula-ganadera-fe1500',
    name: 'Bascula Ganadera FE-1500',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Bascula ganadera electronica con capacidad de 1,500 kg. Sistema de 4 celdas de carga tipo shear beam con indicador digital y funcion estabilizadora de peso.',
    specs: ['Capacidad: 1,500 kg', 'Celdas: 4 shear beam (2.5 klb c/u)', 'Tipo: Electronica', 'Indicador: Digital'],
    features: ['Funcion estabilizadora', 'Pesaje en segundos', 'Cubierta anti-golpes', 'Anti-corrosion'],
    image: 'scale-cattle-electronic',
  },
  {
    id: 'bascula-ganadera-cui1500',
    name: 'Bascula Ganadera CUI-1500',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Bascula ganadera mecanica con capacidad de 1,500 kg. Fabricada en acero galvanizado, no requiere electricidad. Diseño probado por mas de 50 años.',
    specs: ['Capacidad: 1,500 kg', 'Material: Acero galvanizado', 'Tipo: Mecanica', 'Electricidad: No requiere'],
    features: ['Sin electricidad', 'Estructura robusta', '50 años de diseño', 'Multi-especie'],
    image: 'scale-cattle-mech',
  },
  {
    id: 'bascula-ganadera-3000',
    name: 'Bascula Ganadera 3000 kg',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Bascula ganadera de alta capacidad para ganado mayor. Plataforma amplia de hasta 3 metros con precision de 0.5 kg.',
    specs: ['Capacidad: 3,000 kg', 'Plataforma: Hasta 3 m', 'Precision: 0.5 kg', 'Alimentacion: 220V'],
    features: ['Alta capacidad', 'Plataforma amplia', 'Alta precision', 'Funciones avanzadas'],
    image: 'scale-cattle-heavy',
  },
  {
    id: 'bascula-ganadera-portatil',
    name: 'Bascula Ganadera Portatil',
    category: 'Basculas Ganaderas',
    categoryId: 'ganaderas',
    description: 'Bascula ganadera portatil ideal para trabajos en campo. Facil de transportar e instalar en diferentes ubicaciones.',
    specs: ['Capacidad: 500-1500 kg', 'Tipo: Portatil', 'Instalacion: Rapida', 'Transporte: Facil'],
    features: ['Portatil y liviana', 'Instalacion rapida', 'Uso en campo', 'Tara y hold'],
    image: 'scale-cattle-portable',
  },
  {
    id: 'bascula-camionera-standard',
    name: 'Bascula Camionera Estandar',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Bascula camionera de diseño y fabricacion a medida. Alta capacidad para vehiculos pesados con sistemas de dosificacion integrados.',
    specs: ['Capacidad: A medida', 'Diseño: Personalizado', 'Integracion: Software camionero', 'Dosificacion: Integrada'],
    features: ['Diseño a medida', 'Alta capacidad', 'Software integrado', 'Dosificacion automatica'],
    image: 'scale-truck',
  },
  {
    id: 'bascula-ferroviaria',
    name: 'Bascula Ferroviaria',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Bascula ferroviaria con capacidad de hasta 120 toneladas para pesaje de vagones y locomotoras.',
    specs: ['Capacidad: Hasta 120 ton', 'Uso: Ferroviario', 'Tipo: Pesaje en via', 'Precision: Certificada'],
    features: ['120 toneladas', 'Pesaje en via', 'Precision certificada', 'Uso industrial'],
    image: 'scale-rail',
  },
  {
    id: 'sistema-pesaje-tanques',
    name: 'Sistema Pesaje de Tanques',
    category: 'Basculas Camioneras',
    categoryId: 'camioneras',
    description: 'Sistema de pesaje para tanques y silos con monitoreo continuo e integracion con sistemas de control.',
    specs: ['Tipo: Tanques y silos', 'Monitoreo: Continuo', 'Integracion: Sistemas de control', 'Automatizacion: Si'],
    features: ['Monitoreo continuo', 'Integracion completa', 'Control automatizado', 'Alta precision'],
    image: 'scale-tank',
  },
  {
    id: 'dinamometro-10ton',
    name: 'Dinamometro Digital 10 Ton',
    category: 'Dinamometros',
    categoryId: 'dinamometros',
    description: 'Dinamometro digital con capacidad de hasta 10 toneladas. Carcasa robusta con bateria de 60 horas y control remoto incluido.',
    specs: ['Capacidad: Hasta 10 ton', 'Bateria: 60 horas', 'Control: Remoto incluido', 'Tipo: Digital'],
    features: ['Carcasa robusta', '60 horas bateria', 'Control remoto', 'Funciones avanzadas'],
    image: 'dynamometer',
  },
  {
    id: 'dinamometro-5ton',
    name: 'Dinamometro Digital 5 Ton',
    category: 'Dinamometros',
    categoryId: 'dinamometros',
    description: 'Dinamometro digital de capacidad media, ideal para aplicaciones industriales que requieren medicion de fuerza y peso en suspension.',
    specs: ['Capacidad: 5 ton', 'Display: Digital LED', 'Bateria: Recargable', 'Precision: Alta'],
    features: ['Digital LED', 'Bateria recargable', 'Alta precision', 'Portatil'],
    image: 'dynamometer-5',
  },
  {
    id: 'dinamometro-portatil',
    name: 'Dinamometro Portatil',
    category: 'Dinamometros',
    categoryId: 'dinamometros',
    description: 'Dinamometro portatil para mediciones en campo. Compacto, liviano y de facil operacion.',
    specs: ['Tipo: Portatil', 'Peso: Liviano', 'Operacion: Facil', 'Uso: Campo'],
    features: ['Compacto', 'Liviano', 'Facil operacion', 'Uso en campo'],
    image: 'dynamometer-portable',
  },
  {
    id: 'indicador-digital',
    name: 'Indicador Digital',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Indicador digital de alta visibilidad para basculas. Display LED grande con multiples funciones de pesaje.',
    specs: ['Display: LED alta visibilidad', 'Funciones: Multiples', 'Compatibilidad: Universal', 'Conexion: Estandar'],
    features: ['Alta visibilidad', 'Multiples funciones', 'Compatible universal', 'Facil instalacion'],
    image: 'indicator',
  },
  {
    id: 'celdas-carga',
    name: 'Celdas de Carga',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Celdas de carga de alta precision para basculas industriales. Diferentes capacidades y tipos disponibles.',
    specs: ['Tipo: Shear beam, Single point', 'Capacidades: Variables', 'Material: Acero inoxidable', 'Precision: Alta'],
    features: ['Alta precision', 'Multiples tipos', 'Acero inoxidable', 'Larga duracion'],
    image: 'loadcell',
  },
  {
    id: 'pesas-patron',
    name: 'Pesas Patron Certificadas',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Pesas patron certificadas para calibracion y verificacion de basculas. Certificacion ONAC disponible.',
    specs: ['Certificacion: ONAC', 'Clases: Multiples', 'Material: Acero inoxidable', 'Trazabilidad: SI'],
    features: ['Certificadas ONAC', 'Multiples clases', 'Trazabilidad', 'Alta precision'],
    image: 'weights',
  },
  {
    id: 'display-remoto',
    name: 'Display Remoto LED',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Display LED remoto de alta visibilidad para visualizacion de peso a distancia. Ideal para plantas industriales.',
    specs: ['Tipo: LED remoto', 'Visibilidad: Alta', 'Alcance: Largo', 'Instalacion: Pared o poste'],
    features: ['Visibilidad a distancia', 'LED brillante', 'Facil instalacion', 'Uso industrial'],
    image: 'display',
  },
  {
    id: 'cajas-union',
    name: 'Cajas de Union',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Cajas de union para conexion de multiples celdas de carga. Fabricadas en acero inoxidable con ajuste de señal.',
    specs: ['Material: Acero inoxidable', 'Capacidad: Multiples celdas', 'Ajuste: De señal', 'Proteccion: IP65'],
    features: ['Acero inoxidable', 'Multiples celdas', 'Ajuste de señal', 'IP65'],
    image: 'junction',
  },
  {
    id: 'repuestos',
    name: 'Repuestos Originales',
    category: 'Perifericos y Accesorios',
    categoryId: 'perifericos',
    description: 'Repuestos originales Prometalicos para mantenimiento y reparacion de basculas. Garantia de fabrica.',
    specs: ['Tipo: Originales', 'Garantia: De fabrica', 'Disponibilidad: Stock', 'Envio: Nacional'],
    features: ['Originales de fabrica', 'Garantia incluida', 'Stock disponible', 'Envio nacional'],
    image: 'spares',
  },
  {
    id: 'software-camionero',
    name: 'Software Camionero',
    category: 'Software',
    categoryId: 'software',
    description: 'Software especializado para gestion de pesaje camionero. Control de tickets, reportes y administracion completa.',
    specs: ['Tipo: Gestion camionero', 'Reportes: Completos', 'Tickets: Automaticos', 'Base datos: Integrada'],
    features: ['Gestion completa', 'Reportes automaticos', 'Control de tickets', 'Base de datos'],
    image: 'software-truck',
  },
  {
    id: 'software-molinos',
    name: 'Software para Molinos',
    category: 'Software',
    categoryId: 'software',
    description: 'Software especializado para operaciones de molinos. Gestion de pesaje, dosificacion y control de procesos.',
    specs: ['Tipo: Molinos', 'Control: Procesos', 'Dosificacion: Integrada', 'Reportes: Si'],
    features: ['Gestion de molinos', 'Control de procesos', 'Dosificacion', 'Reportes'],
    image: 'software-mill',
  },
  {
    id: 'software-peajes',
    name: 'Software de Peajes',
    category: 'Software',
    categoryId: 'software',
    description: 'Sistema para gestion de peajes con pesaje integrado. Control de paso, cobro y reportes automaticos.',
    specs: ['Tipo: Peajes', 'Pesaje: Integrado', 'Cobro: Automatico', 'Reportes: Tiempo real'],
    features: ['Gestion de peajes', 'Pesaje integrado', 'Cobro automatico', 'Tiempo real'],
    image: 'software-toll',
  },
  {
    id: 'software-medida',
    name: 'Software a la Medida',
    category: 'Software',
    categoryId: 'software',
    description: 'Desarrollo de software personalizado segun las necesidades especificas de su operacion de pesaje y control.',
    specs: ['Tipo: Personalizado', 'Desarrollo: A medida', 'Integracion: Total', 'Soporte: Incluido'],
    features: ['Desarrollo personalizado', 'Integracion total', 'Soporte incluido', 'Escalable'],
    image: 'software-custom',
  },
];

export const services: Service[] = [
  {
    id: 'calibracion',
    name: 'Calibracion y Metrologia',
    icon: 'analytics-outline',
    description: 'Primer laboratorio de metrologia industrial en Colombia. Calibracion con certificacion ONAC bajo norma ISO/IEC 17025:2017.',
    details: [
      'Certificacion ONAC (09-LAC-013 y 23-LAB-004)',
      'Norma ISO/IEC 17025:2017',
      'Calibracion de basculas e instrumentos',
      'Venta de pesas patron certificadas',
      'Procedimientos bajo guia SIM y NTC 1848',
      'Pasantias en metrologia',
    ],
  },
  {
    id: 'servicio-tecnico',
    name: 'Servicio Tecnico',
    icon: 'construct-outline',
    description: 'Servicio tecnico especializado con cobertura nacional e internacional. Instalacion, mantenimiento y reparacion.',
    details: [
      'Instalacion profesional',
      'Mantenimiento preventivo y correctivo',
      'Inspeccion y diagnostico',
      'Repuestos originales',
      'Cobertura nacional e internacional',
      'Actualizacion tecnica',
    ],
  },
  {
    id: 'alquiler',
    name: 'Alquiler de Equipos',
    icon: 'swap-horizontal-outline',
    description: 'Alquiler de basculas y equipos de pesaje para proyectos temporales o necesidades especificas.',
    details: [
      'Basculas industriales',
      'Basculas ganaderas',
      'Dinamometros',
      'Proyectos temporales',
      'Soporte tecnico incluido',
      'Disponibilidad inmediata',
    ],
  },
  {
    id: 'asesoria',
    name: 'Asesoria Tecnica',
    icon: 'school-outline',
    description: 'Asesoria especializada para seleccionar la solucion de pesaje ideal segun su necesidad y presupuesto.',
    details: [
      'Evaluacion de necesidades',
      'Recomendacion de equipos',
      'Diseño de soluciones a medida',
      'Capacitacion de personal',
      'Acompañamiento en implementacion',
      'Soporte post-venta',
    ],
  },
];

export const companyInfo = {
  name: 'Prometalicos S.A.',
  tagline: 'Expertos en Pesaje y Control',
  years: '50+',
  phone: '+57 606 886 4009',
  email: 'ventas@prometalicos.com',
  whatsapp: '+573001234567',
  address: 'Cra 21 N 72-04 Zona Industrial Alta Suiza, Manizales, Colombia',
  website: 'www.prometalicos.com',
  certifications: [
    'Acreditacion ONAC (09-LAC-013)',
    'Acreditacion ONAC (23-LAB-004)',
    'ISO/IEC 17025:2017',
    'ISO 9001',
    'OIML',
    'NTC 2031',
    'CE',
  ],
  advantages: [
    'Mas de 50 años de experiencia',
    'Fabricacion nacional colombiana',
    'Diseño y fabricacion a medida',
    'Productos 100% reparables',
    'Envios a toda Colombia e internacional',
    'Servicio tecnico especializado',
    'Laboratorio acreditado ONAC',
    'Innovacion constante',
  ],
  sectors: [
    'Agroindustria',
    'Alimentos',
    'Puertos',
    'Operadores logisticos',
    'Estaciones de pesaje',
    'Ganaderia',
    'Fabricas',
    'Hosteleria',
  ],
};
